package functionalities;

import objects.Currency;
import utils.MessageIDGenerator;

import java.nio.ByteBuffer;
import java.nio.charset.StandardCharsets;
import java.util.Scanner;

import static utils.Constants.*;
import static utils.SocketFunctions.*;
import static utils.UtilityFunctions.concatWithCopy;
import static utils.UtilityFunctions.convertStringToByteArray;


public class ClientInterface {
    public static MessageIDGenerator gen = new MessageIDGenerator(MESSAGE_ID_LENGTH);   // create a new MessageIDGenerator

    /**
     * Function to process account creation
     *
     * @param name              String containing name of the customer
     * @param currency          Enum to represent the currency of the bank account
     * @param password          String to represent password of the bank account
     * @param initialAccBalance String to represent inital account balance
     * @return the bank account number generated by the server
     */
    public static int createAccount(String name, Currency currency, String password, String initialAccBalance,boolean atLeastOnce) {
        Scanner scanner = new Scanner(System.in);

        System.out.println("Enter your name");


        int nameLength = name.length();
        int currencyLength = currency.toString().length();
        int accBalanceLength = initialAccBalance.length();
        int passwordLength = password.length();

        byte[] accCreationByteArray = ByteBuffer.allocate(BYTE_BLOCK_SIZE_FOR_INT).putInt(ACC_OPENING_CODE).array();

        byte[] nameLengthByteArray = ByteBuffer.allocate(BYTE_BLOCK_SIZE_FOR_INT).putInt(nameLength).array();
        byte[] nameByteArray = convertStringToByteArray(name);

        byte[] currencyLengthByteArray = ByteBuffer.allocate(BYTE_BLOCK_SIZE_FOR_INT).putInt(currencyLength).array();
        byte[] currencyByteArray = convertStringToByteArray(currency.toString());

        byte[] passwordLengthByteArray = ByteBuffer.allocate(BYTE_BLOCK_SIZE_FOR_INT).putInt(passwordLength).array();
        byte[] passwordByteArray = convertStringToByteArray(password);

        byte[] accBalanceLengthByteArray = ByteBuffer.allocate(BYTE_BLOCK_SIZE_FOR_INT).putInt(accBalanceLength).array();
        byte[] accBalanceArray = convertStringToByteArray(initialAccBalance);

        String messageID = gen.nextString();
        System.out.println(messageID);
        byte[] messageIDArray = convertStringToByteArray(messageID);

        byte[] marshall = concatWithCopy(messageIDArray, accCreationByteArray, nameLengthByteArray, nameByteArray, currencyLengthByteArray, currencyByteArray, passwordLengthByteArray, passwordByteArray, accBalanceLengthByteArray, accBalanceArray);
        for (byte c : marshall) {
            System.out.printf("%02X ", c);      // printing to show the marshalled data on console
        }
        System.out.println();
        byte[] reply = sendRequest(marshall,atLeastOnce);

        ByteBuffer choiceBuffer = ByteBuffer.allocate(BUFFER_SIZE);
        choiceBuffer.put(reply);
        choiceBuffer.rewind();
        return choiceBuffer.getInt();
    }

    /**
     * Function to query current account balance
     *
     * @param accNumber the account number of the account to be queried
     * @param password  the password of the account to be queried
     * @return the current balance in the account
     */
    public static double queryAccBalance(String accNumber, String password,boolean atLeastOnce) {
        int accNumberLength = accNumber.length();
        int passwordLength = password.length();

        byte[] accBalanceQueryByteArray = ByteBuffer.allocate(BYTE_BLOCK_SIZE_FOR_INT).putInt(ACC_BALANCE_CODE).array();

        byte[] accNumberLengthByteArray = ByteBuffer.allocate(BYTE_BLOCK_SIZE_FOR_INT).putInt(accNumberLength).array();
        byte[] accNumberByteArray = convertStringToByteArray(accNumber);

        byte[] passwordLengthByteArray = ByteBuffer.allocate(BYTE_BLOCK_SIZE_FOR_INT).putInt(passwordLength).array();
        byte[] passwordByteArray = convertStringToByteArray(password);

        String messageID = gen.nextString();
        System.out.println(messageID);
        byte[] messageIDArray = convertStringToByteArray(messageID);

        byte[] marshall = concatWithCopy(messageIDArray, accBalanceQueryByteArray, accNumberLengthByteArray, accNumberByteArray, passwordLengthByteArray, passwordByteArray);
        for (byte c : marshall) {
            System.out.printf("%02X ", c);      // printing to show the marshalled data on console
        }
        System.out.println();
        byte[] reply = sendRequest(marshall,atLeastOnce);

        double currentAccBalance = ByteBuffer.wrap(reply).getDouble();
        System.out.println("current account balance: " + currentAccBalance);
        return currentAccBalance;
    }

    public static String closeAccount(String name, String password, String accNumber,boolean atLeastOnce) {
        int nameLength = name.length();
        int passwordLength = password.length();
        int accNumberLength = accNumber.length();

        byte[] closeAccByteArray = ByteBuffer.allocate(BYTE_BLOCK_SIZE_FOR_INT).putInt(ACC_CLOSING_CODE).array();

        byte[] accNumberLengthByteArray = ByteBuffer.allocate(BYTE_BLOCK_SIZE_FOR_INT).putInt(accNumberLength).array();
        byte[] accNumberByteArray = convertStringToByteArray(accNumber);

        byte[] nameLengthByteArray = ByteBuffer.allocate(BYTE_BLOCK_SIZE_FOR_INT).putInt(nameLength).array();
        byte[] nameByteArray = convertStringToByteArray(name);

        byte[] passwordLengthByteArray = ByteBuffer.allocate(BYTE_BLOCK_SIZE_FOR_INT).putInt(passwordLength).array();
        byte[] passwordByteArray = convertStringToByteArray(password);

        String messageID = gen.nextString();
        System.out.println(messageID);
        byte[] messageIDArray = convertStringToByteArray(messageID);

        byte[] marshall = concatWithCopy(messageIDArray, closeAccByteArray, accNumberLengthByteArray, accNumberByteArray, nameLengthByteArray, nameByteArray, passwordLengthByteArray, passwordByteArray);
        for (byte c : marshall) {
            System.out.printf("%02X ", c);      // printing to show the marshalled data on console
        }
        System.out.println();
        String reply = new String(sendRequest(marshall,atLeastOnce), StandardCharsets.UTF_8);

        if (reply.equals(accNumber)) {
            return "Account Number " + reply + " has been closed successfully";
        }

        return " ";
    }

    public static double depositMoney(String name, int accNumber,String password,Currency currency, double deposit,boolean atLeastOnce) {
        int nameLength = name.length();
        int accNumberLength = Integer.toString(accNumber).length();
        int passwordLength = password.length();
        int currencyLength = currency.toString().length();
        int depositLength = String.valueOf(deposit).length();
        
        byte[] depositMoneyByteArray = ByteBuffer.allocate(4).putInt(2).array();
        byte[] nameLengthByteArray = ByteBuffer.allocate(4).putInt(nameLength).array();
        byte[] nameByteArray = convertStringToByteArray(name);
        byte[] accNumberLengthByteArray = ByteBuffer.allocate(4).putInt(accNumberLength).array();
        byte[] accNumberByteArray = convertStringToByteArray(Integer.toString(accNumber));
        byte[] passwordLengthByteArray = ByteBuffer.allocate(4).putInt(passwordLength).array();
        byte[] passwordByteArray = convertStringToByteArray(password);
        byte[] currencyLengthByteArray = ByteBuffer.allocate(4).putInt(currencyLength).array();
        byte[] currencyByteArray = convertStringToByteArray(currency.toString());
        byte[] depositLengthByteArray = ByteBuffer.allocate(4).putInt(depositLength).array();
        byte[] depositByteArray = convertStringToByteArray(String.valueOf(deposit));
            
        String messageID = gen.nextString();
        System.out.println("MessageId: "+messageID);
        byte[] messageIDArray = convertStringToByteArray(messageID);
    
        byte[] marshall = concatWithCopy(messageIDArray, depositMoneyByteArray, nameLengthByteArray, nameByteArray,accNumberLengthByteArray,accNumberByteArray,passwordLengthByteArray, passwordByteArray,currencyLengthByteArray, currencyByteArray,depositLengthByteArray,depositByteArray);
    
        byte[] reply = sendRequest(marshall,atLeastOnce);
        if (atLeastOnce){
            while(reply==null){
                reply=sendRequest(marshall, atLeastOnce);
                System.out.println("Resending MessageId: "+messageID);
            }
        }
        double currentAccBalance = ByteBuffer.wrap(reply).getDouble();
        System.out.println("Current account balance: " + currentAccBalance);
        return currentAccBalance;
    }
    public static double withdrawMoney(String name, int accNumber,String password,Currency currency, double withdraw,boolean atLeastOnce) {
        int nameLength = name.length();
        int accNumberLength = Integer.toString(accNumber).length();
        int passwordLength = password.length();
        int currencyLength = currency.toString().length();
        int withdrawLength = String.valueOf(withdraw).length();
        
        byte[] withdrawMoneyByteArray = ByteBuffer.allocate(4).putInt(3).array();
        byte[] nameLengthByteArray = ByteBuffer.allocate(4).putInt(nameLength).array();
        byte[] nameByteArray = convertStringToByteArray(name);
        byte[] accNumberLengthByteArray = ByteBuffer.allocate(4).putInt(accNumberLength).array();
        byte[] accNumberByteArray = convertStringToByteArray(Integer.toString(accNumber));
        byte[] passwordLengthByteArray = ByteBuffer.allocate(4).putInt(passwordLength).array();
        byte[] passwordByteArray = convertStringToByteArray(password);
        byte[] currencyLengthByteArray = ByteBuffer.allocate(4).putInt(currencyLength).array();
        byte[] currencyByteArray = convertStringToByteArray(currency.toString());
        byte[] withdrawLengthByteArray = ByteBuffer.allocate(4).putInt(withdrawLength).array();
        byte[] withdrawByteArray = convertStringToByteArray(String.valueOf(withdraw));
            
        String messageID = gen.nextString();
        System.out.println("MessageId: "+messageID);
        byte[] messageIDArray = convertStringToByteArray(messageID);
    
        byte[] marshall = concatWithCopy(messageIDArray, withdrawMoneyByteArray, nameLengthByteArray, nameByteArray,accNumberLengthByteArray,accNumberByteArray,passwordLengthByteArray, passwordByteArray,currencyLengthByteArray, currencyByteArray,withdrawLengthByteArray,withdrawByteArray);
    
        byte[] reply = sendRequest(marshall,atLeastOnce);
        if (atLeastOnce){
            while(reply==null){
                reply=sendRequest(marshall, atLeastOnce);
                System.out.println("Resending MessageId: "+messageID);
            }
        }
        double currentAccBalance = ByteBuffer.wrap(reply).getDouble();
        System.out.println("Current account balance: " + currentAccBalance);
        return currentAccBalance;
    }

    public static double transferMoney(String name, int accNumber,String password,int toAccNumber,Currency currency, double withdraw,boolean atLeastOnce) {
        int nameLength = name.length();
        int accNumberLength = Integer.toString(accNumber).length();
        int passwordLength = password.length();
        int toAccNumberLength = Integer.toString(toAccNumber).length();
        int currencyLength = currency.toString().length();
        int withdrawLength = String.valueOf(withdraw).length();
        
        byte[] withdrawMoneyByteArray = ByteBuffer.allocate(4).putInt(3).array();
        byte[] nameLengthByteArray = ByteBuffer.allocate(4).putInt(nameLength).array();
        byte[] nameByteArray = convertStringToByteArray(name);
        byte[] accNumberLengthByteArray = ByteBuffer.allocate(4).putInt(accNumberLength).array();
        byte[] accNumberByteArray = convertStringToByteArray(Integer.toString(accNumber));
        byte[] passwordLengthByteArray = ByteBuffer.allocate(4).putInt(passwordLength).array();
        byte[] passwordByteArray = convertStringToByteArray(password);
        byte[] toAccNumberLengthByteArray = ByteBuffer.allocate(4).putInt(toAccNumberLength).array();
        byte[] toAccNumberByteArray = convertStringToByteArray(Integer.toString(toAccNumber));
        byte[] currencyLengthByteArray = ByteBuffer.allocate(4).putInt(currencyLength).array();
        byte[] currencyByteArray = convertStringToByteArray(currency.toString());
        byte[] withdrawLengthByteArray = ByteBuffer.allocate(4).putInt(withdrawLength).array();
        byte[] withdrawByteArray = convertStringToByteArray(String.valueOf(withdraw));
            
        String messageID = gen.nextString();
        System.out.println("MessageId: "+messageID);
        byte[] messageIDArray = convertStringToByteArray(messageID);
    
        byte[] marshall = concatWithCopy(messageIDArray, withdrawMoneyByteArray, nameLengthByteArray, nameByteArray,accNumberLengthByteArray,accNumberByteArray,passwordLengthByteArray, passwordByteArray,toAccNumberLengthByteArray,toAccNumberByteArray,currencyLengthByteArray, currencyByteArray,withdrawLengthByteArray,withdrawByteArray);
    
        byte[] reply = sendRequest(marshall,atLeastOnce);
        if (atLeastOnce){
            while(reply==null){
                reply=sendRequest(marshall, atLeastOnce);
                System.out.println("Resending MessageId: "+messageID);
            }
        }
        double currentAccBalance = ByteBuffer.wrap(reply).getDouble();
        System.out.println("Current account balance: " + currentAccBalance);
        return currentAccBalance;
    }
}
